name: Generate a build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build on main branch
        run: npm run build

      - name: Copy dist contents to build branch
        run: |
          git checkout build
          git rm -r .
          git checkout main -- dist/
          mv dist/* .
          git add .
          git commit -m "Update build branch with dist contents from main branch"
          git push origin build
